cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: joseitti
    osta:
      email: bautistaosta1@gmail.com
      name: Osta
      password: $2b$12$aMGsOMLvWV97AecjjVDS.eO3pKS2T/vTRx1R.WcG5y8x2rBIUkZii
    osthailyd:
      email: bautistaosta1@gmail.com
      name: Osthailyd Bautista
      password: levtarasov
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: isabelitti
preauthorized:
  emails:
  - melsby@gmail.com
